name: Build Nightly Packages

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/build-nightly.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run build:nightly
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
