name: Publish nightly version

on:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed
    branches:
      - main

jobs:
  publish_npm:
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: cache-npm-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run publish:nightly
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  publish_macos:
    needs: [publish_npm]
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        run: |
          cd app/desktop
          npm install
          npm run publish:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Slashnotes-mac-x64
          path: app/desktop/dist/Slashnotes-1.0.0.dmg
          if-no-files-found: error
  publish_win:
    needs: [publish_npm]
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        run: |
          cd app/desktop
          npm install
          npm run publish:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Slashnotes-win-x64
          path: app/desktop/dist/Slashnotes 1.0.0.exe
          if-no-files-found: error
