name: Nightly packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/nightly.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Test
        run: |
          CI=true npm run test
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run publish:nightly
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
