name: Testing

on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/**
      - packages/**
      - package.json
      - package-lock.json
      - .github/workflows/testing.yml
  push:
    paths:
      - app/**
      - packages/**
      - package.json
      - package-lock.json
      - .github/workflows/testing.yml
      - .github/workflows/nightly.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - uses: actions/cache@v3
        id: cache-npm-install
        with:
          path: ./*
          key: ${{ github.sha }}
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - uses: actions/cache@v3
        id: cache-npm-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Test
        run: |
          npm run ci
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOVTOKEN }}
